### ISSUE TITLE
Example template, login exception. UserId not found

### ISSUE THREAD

**Issue by gecode-es** [pacal/NPocoIdentity_WebApp_Template#1]
Getting the following exception when logging in as a newly created user using the example template project.

```
Exception Details: System.InvalidOperationException: UserId not found.

Source Error: 


Line 77:             // This doesn't count login failures towards account lockout
Line 78:             // To enable password failures to trigger account lockout, change to shouldLockout: true
Line 79:             var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);
Line 80:             switch (result)
Line 81:             {

Source File: C:\Users\markb\Desktop\NPocoIdentity_WebApp_Template-Implement_INPocoIdentity\NPocoIdentityWebAppTemplate\Controllers\AccountController.cs    Line: 79 
```

**Comment by pacal** [comment]
@alanda sorry about that. I am able to reproduce this as well. I will take a look at the issue in a bit an push out a fix.. Thanks again.

**Comment by pacal** [comment]
@alanda ok. it was a missing setter for the custom identity user implementation. Please pull or download the zip and try again. I will also add tests to the NPoco_Identity_Provider project for custom user implementations. Appreciate your feed back.

**Comment by gecode-es** [comment]
That's fantastic. Keep up the great work. Thanks
